CREATE TABLE IF NOT EXISTS item (
id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(40)    NOT NULL,
status VARCHAR(10)   NOT NULL
);


CREATE TABLE IF NOT EXISTS audit_item (
id BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT PRIMARY KEY,
action VARCHAR(8)        NOT NULL,
item_id BIGINT UNSIGNED  NOT NULL,
date DATETIME            NOT NULL
);
